services:
  aikido-web:
    build:
      dockerfile: ./docker/web.dockerfile
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    depends_on:
      - aikido-postgres

  aikido-postgres:
    image: postgres:17.3
    volumes:
      - aikido-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "54321:5432"

volumes:
  aikido-postgres: